global using ConsoleAppVisuals;
global using ConsoleAppVisuals.Enums;
global using ConsoleAppVisuals.InteractiveElements;
global using ConsoleAppVisuals.PassiveElements;
global using LivInParisRoussilleTeynier.Data;
global using LivInParisRoussilleTeynier.Data.Attributes;
global using LivInParisRoussilleTeynier.Models.Enums;
global using LivInParisRoussilleTeynier.Models.Maps;
global using LivInParisRoussilleTeynier.UI;
