using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LivInParisRoussilleTeynier.Domain.Models.Order;

/// <summary>
/// Represents an account in the system.
/// </summary>
[Table("Account")]
[Index(nameof(AccountUserName), IsUnique = true, Name = "IX_Account_User_Name")]
public class Account
{
    /// <summary>
    /// The primary key for the account.
    /// </summary>
    /// <remarks>
    /// This value is generated by the database on insert.
    /// </remarks>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Column("account_id")]
    public int AccountId { get; set; }

    /// <summary>
    /// Unique user name of the account.
    /// </summary>
    [Required]
    [MaxLength(100)]
    [Column("account_user_name")]
    public required string AccountUserName { get; set; }

    /// <summary>
    /// Password of the account.
    /// </summary>
    [Required]
    [MaxLength(50)]
    [Column("account_password")]
    public required string AccountPassword { get; set; }
}
