using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LivInParisRoussilleTeynier.Domain.Models.Order;

/// <summary>
/// Represents an account in the system.
/// </summary>
[Table("Account")]
[Index(nameof(AccountEmail), IsUnique = true, Name = "IX_Account_Email")]
public class Account
{
    /// <summary>
    /// The primary key for the account.
    /// </summary>
    /// <remarks>
    /// This value is generated by the database on insert.
    /// </remarks>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int AccountId { get; set; }

    /// <summary>
    /// Unique email address of the account.
    /// </summary>
    [Required]
    [MaxLength(100)]
    public required string AccountEmail { get; set; }

    /// <summary>
    /// Password of the account.
    /// </summary>
    [Required]
    [MaxLength(50)]
    public required string AccountPassword { get; set; }
}
