using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using LivInParisRoussilleTeynier.Domain.Models.Maps;
using Microsoft.EntityFrameworkCore;

namespace LivInParisRoussilleTeynier.Domain.Models.Order;

/// <summary>
/// Represents an address in the system.
/// </summary>
[Table("Address")]
[Index(nameof(AddressNumber), nameof(Street), IsUnique = true, Name = "IX_Address_Number_Street")]
public class Address
{
    /// <summary>
    /// The primary key for the address.
    /// </summary>
    /// <remarks>
    /// This value is generated by the database on insert.
    /// </remarks>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int AddressId { get; set; }

    /// <summary>
    /// The number of the address.
    /// </summary>
    [Required]
    [Range(1, int.MaxValue, ErrorMessage = "Address number must be positive.")]
    public required int AddressNumber { get; set; }

    /// <summary>
    /// The street name of the address.
    /// </summary>
    [Required]
    [MaxLength(100)]
    public required string Street { get; set; }

    /// <summary>
    /// The nearest station to the address.
    /// </summary>
    [MaxLength(50)]
    public Station? NearestStation { get; set; }

    /// <summary>
    /// Chefs associated with this address.
    /// </summary>
    public ICollection<Chef> Chefs { get; set; } = new List<Chef>();

    /// <summary>
    /// Individuals associated with this address.
    /// </summary>
    public ICollection<Individual> Individuals { get; set; } = new List<Individual>();

    /// <summary>
    /// Orders associated with this address.
    /// </summary>
    public ICollection<OrderLine> OrderLines { get; set; } = new List<OrderLine>();
}
