using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using LivInParisRoussilleTeynier.Domain.Models.Order.Enums;

namespace LivInParisRoussilleTeynier.Domain.Models.Order;

/// <summary>
/// Represents a dish in the system.
/// </summary>
[Table("Dish")]
public class Dish
{
    /// <summary>
    /// The primary key for the dish.
    /// </summary>
    /// <remarks>
    /// This value is generated by the database on insert.
    /// </remarks>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int DishId { get; set; }

    /// <summary>
    /// The name of the dish.
    /// </summary>
    [Required]
    [MaxLength(50)]
    public required string DishName { get; set; }

    /// <summary>
    /// The type of the dish.
    /// </summary>
    [Required]
    public required DishType DishType { get; set; }

    /// <summary>
    /// The time in days before the dish expires.
    /// </summary>
    [Required]
    public required int ExpiryTime { get; set; }

    /// <summary>
    /// The nationality of the dish's cuisine.
    /// </summary>
    [Required]
    [MaxLength(50)]
    public required string CuisineNationality { get; set; }

    //HACK: enum CuisineNationality
    /// <summary>
    /// The quantity of the dish available.
    /// </summary>
    [Required]
    [Range(1, int.MaxValue, ErrorMessage = "Quantity must be positive.")]
    public required int Quantity { get; set; }

    /// <summary>
    /// The price of the dish.
    /// </summary>
    [Required]
    [Range(0, 10E9, ErrorMessage = "Price must be zero or positive.")]
    [Column(TypeName = "decimal(10,2)")]
    public required decimal Price { get; set; }

    /// <summary>
    /// The farest origin of the ingredients of the dish.
    /// </summary>
    [Required]
    public required ProductsOrigin ProductsOrigin { get; set; }

    /// <summary>
    /// The path to the photo of the dish.
    /// </summary>
    [MaxLength(255)]
    public string PhotoPath { get; set; } = "null.png";

    /// <summary>
    /// The order lines associated with this dish.
    /// </summary>
    public ICollection<OrderLine> OrderLines { get; set; } = new List<OrderLine>();

    /// <summary>
    /// The menu proposals associated with this dish.
    /// </summary>
    public ICollection<MenuProposal> MenuProposals { get; set; } = new List<MenuProposal>();

    /// <summary>
    /// The contains associated with this dish.
    /// </summary>
    public ICollection<Contains> Contains { get; set; } = new List<Contains>();
}
