using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LivInParisRoussilleTeynier.Domain.Models.Order;

/// <summary>
/// Represents an ingredient used in one or more dishes.
/// </summary>
[Table("Ingredient")]
[Index(nameof(IngredientName), IsUnique = true, Name = "IX_Ingredient_Name")]
public class Ingredient
{
    /// <summary>
    /// The primary key for the ingredient.
    /// </summary>
    /// <remarks>
    /// This value is generated by the database on insert.
    /// </remarks>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Column("ingredient_id")]
    public int IngredientId { get; set; }

    /// <summary>
    /// The name of the ingredient.
    /// </summary>
    [Required]
    [MaxLength(50)]
    [Column("ingredient_name")]
    public required string IngredientName { get; set; }

    /// <summary>
    /// A value indicating whether this ingredient is suitable for vegetarians.
    /// </summary>
    [Required]
    [Column("is_vegetarian")]
    public bool IsVegetarian { get; set; }

    /// <summary>
    /// A value indicating whether this ingredient is suitable for vegans.
    /// </summary>
    [Required]
    [Column("is_vegan")]
    public bool IsVegan { get; set; }

    /// <summary>
    /// A value indicating whether this ingredient is gluten-free.
    /// </summary>
    [Required]
    [Column("is_gluten_free")]
    public bool IsGlutenFree { get; set; }

    /// <summary>
    /// A value indicating whether this ingredient is lactose-free.
    /// </summary>
    [Required]
    [Column("is_lactose_free")]
    public bool IsLactoseFree { get; set; }

    /// <summary>
    /// A value indicating whether this ingredient is halal.
    /// </summary>
    [Required]
    [Column("is_halal")]
    public bool IsHalal { get; set; }

    /// <summary>
    /// A value indicating whether this ingredient is kosher.
    /// </summary>
    [Required]
    [Column("is_kosher")]
    public bool IsKosher { get; set; }

    /// <summary>
    /// The collection of relationships indicating
    /// which dishes contain this ingredient.
    /// </summary>
    public ICollection<Contains> Contains { get; set; } = new List<Contains>();
}
