using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LivInParisRoussilleTeynier.Domain.Models.Order;

/// <summary>
/// Represents a transaction in the system.
/// </summary>
[Table("OrderTransaction")]
public class OrderTransaction
{
    /// <summary>
    /// The primary key for the transaction.
    /// </summary>
    /// <remarks>
    /// This value is generated by the database on insert.
    /// </remarks>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int TransactionId { get; set; }

    /// <summary>
    /// The Datetime when the transaction was created.
    /// </summary>
    [Required]
    public required DateTime TransactionDatetime { get; set; }

    /// <summary>
    /// The ID of the customer account associated with the transaction.
    /// </summary>
    [Required]
    public required int CustomerAccountId { get; set; }

    /// <summary>
    /// The Customer associated with the transaction.
    /// </summary>
    [ForeignKey("CustomerAccountId")]
    public Customer? Customer { get; set; }

    /// <summary>
    /// The order lines associated with the transaction.
    /// </summary>
    public ICollection<OrderLine> OrderLines { get; set; } = new List<OrderLine>();
}
