using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using LivInParisRoussilleTeynier.Domain.Models.Order.Enums;

namespace LivInParisRoussilleTeynier.Domain.Models.Order;

/// <summary>
/// Represents an order line in the system.
/// </summary>
[Table("OrderLine")]
public class OrderLine
{
    /// <summary>
    /// The primary key for the order line.
    /// </summary>
    /// <remarks>
    /// This value is generated by the database on insert.
    /// </remarks>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int OrderLineId { get; set; }

    /// <summary>
    /// The Datetime when the order line was created.
    /// </summary>
    [Required]
    public required DateTime OrderLineDatetime { get; set; }

    /// <summary>
    /// The Status of the order line.
    /// </summary>
    /// <seealso cref="OrderLineStatus"/>
    [Required]
    public required OrderLineStatus OrderLineStatus { get; set; }

    /// <summary>
    /// The ID of the address where the order will be delivered.
    /// </summary>
    [Required]
    public required int AddressId { get; set; }

    /// <summary>
    /// The ID of the transaction associated with the order line.
    /// </summary>
    [Required]
    public required int TransactionId { get; set; }

    /// <summary>
    /// The ID of the chef account that prepared the order.
    /// </summary>
    [Required]
    public required int ChefAccountId { get; set; }

    /// <summary>
    /// The address associated with the order line.
    /// </summary>
    [ForeignKey("AddressId")]
    public Address? Address { get; set; }

    /// <summary>
    /// The transaction associated with the order line.
    /// </summary>
    [ForeignKey("TransactionId")]
    public OrderTransaction? OrderTransaction { get; set; }

    /// <summary>
    /// The chef account associated with the order line.
    /// </summary>
    [ForeignKey("ChefAccountId")]
    public Chef? Chef { get; set; }

    /// <summary>
    /// The reviews associated with the order line.
    /// </summary>
    public ICollection<Review> Reviews { get; set; } = new List<Review>();
}
