using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using LivInParisRoussilleTeynier.Domain.Models.Order.Enums;

namespace LivInParisRoussilleTeynier.Domain.Models.Order;

/// <summary>
/// Represents a review in the system.
/// </summary>
[Table("Review")]
public class Review
{
    /// <summary>
    /// The primary key for the review.
    /// </summary>
    /// <remarks>
    /// This value is generated by the database on insert.
    /// </remarks>
    [Key]
    [Column("review_id")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int ReviewId { get; set; }

    /// <summary>
    /// The type of the reviewer (customer or chef) of the review.
    /// </summary>
    [Required]
    [Column("reviewer_type")]
    public ReviewerType ReviewerType { get; set; }

    /// <summary>
    /// The rating given by the reviewer.
    /// </summary>
    [Range(1.0, 5.0)]
    [Column("review_rating", TypeName = "decimal(2,1)")]
    public decimal? ReviewRating { get; set; }

    /// <summary>
    /// The comment provided by the reviewer.
    /// </summary>
    [MaxLength(500)]
    [Column("comment")]
    public string? Comment { get; set; }

    /// <summary>
    /// The date when the review was made.
    /// </summary>
    [Required]
    [Column("review_date", TypeName = "date")]
    public required DateOnly? ReviewDate { get; set; } = DateOnly.FromDateTime(DateTime.Now);

    /// <summary>
    /// The ID of the order line associated with the review.
    /// </summary>
    [Required]
    [Column("order_line_id")]
    public required int OrderLineId { get; set; }

    /// <summary>
    /// The order line associated with the review.
    /// </summary>
    [ForeignKey("OrderLineId")]
    public OrderLine? OrderLine { get; set; }
}
