using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LivInParisRoussilleTeynier.Models.Order;

/// <summary>
/// Represents an account in the system.
/// </summary>
[Table("Account")]
[Index(nameof(AccountEmail), IsUnique = true, Name = "IX_Account_Email")]
[Index(nameof(Customer), IsUnique = true, Name = "IX_Account_Customer")]
[Index(nameof(Chef), IsUnique = true, Name = "IX_Account_Chef")]
[Index(nameof(Company), IsUnique = true, Name = "IX_Account_Company")]
[Index(nameof(Individual), IsUnique = true, Name = "IX_Account_Individual")]
public class Account
{
    /// <summary>
    /// The primary key for the account.
    /// </summary>
    /// <remarks>
    /// This value is generated by the database on insert.
    /// </remarks>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int AccountId { get; set; }

    /// <summary>
    /// Unique email address of the account.
    /// </summary>
    [Required]
    [MaxLength(100)]
    public required string AccountEmail { get; set; }

    /// <summary>
    /// Password of the account.
    /// </summary>
    [Required]
    [MaxLength(50)]
    public required string AccountPassword { get; set; }

    /// <summary>
    /// Customer profile associated with the account (if any).
    /// </summary>
    public Customer? Customer { get; set; }

    /// <summary>
    /// Chef profile associated with the account (if any).
    /// </summary>
    public Chef? Chef { get; set; }

    /// <summary>
    /// Company profile associated with the account (if any).
    /// </summary>
    public Company? Company { get; set; }

    /// <summary>
    /// Individual profile associated with the account (if any).
    /// </summary>
    public Individual? Individual { get; set; }
}
