using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LivInParisRoussilleTeynier.Models.Order;

/// <summary>
/// Represents an address in the system.
/// </summary>
[Table("Address")]
[Index(nameof(AddressNumber), nameof(Street), IsUnique = true, Name = "IX_Address_Number_Street")]
public class Address
{
    /// <summary>
    /// The primary key for the address.
    /// </summary>
    /// <remarks>
    /// This value is generated by the database on insert.
    /// </remarks>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int AddressId { get; set; }

    [Required]
    [Range(1, int.MaxValue, ErrorMessage = "Address number must be positive.")]
    public required int AddressNumber { get; set; }

    [Required]
    [MaxLength(50)]
    public required string Street { get; set; }

    [MaxLength(50)]
    public Station? NearestMetro { get; set; }

    /// <summary>
    /// Chefs résidant à cette adresse.
    /// </summary>
    public ICollection<Chef> Chefs { get; set; } = new List<Chef>();

    /// <summary>
    /// Particuliers domiciliés à cette adresse.
    /// </summary>
    public ICollection<Individual> Individuals { get; set; } = new List<Individual>();

    /// <summary>
    /// Lignes de commande pour livraison à cette adresse.
    /// </summary>
    public ICollection<OrderLine> OrderLines { get; set; } = new List<OrderLine>();
}

//TODO: add doc
